### ISSUE TITLE
Running workflows docs - strange guidance on vasp_cmd

### ISSUE THREAD

**Issue by computron** [hackingmaterials/atomate#123]
@bocklund 

At several points in the "Running workflows" tutorials, the docs state:

```
 If your VASP command is anything other than ``vasp_std``, then you'll want to change the line setting the ``VASP_CMD`` key of the configuration dictionary. *Don't use any parallelization software (ibrun, srun, etc.)* it's bad behavior and probably won't work.
```

I don't understand this guidance:
* using srun, mpirun, etc. should work for the vasp_cmd - we do this all the time (although we use env_chk to override the command via my_fworker.yaml - but it's the same thing in the end). So I don't understand the "bad behavior" and "probably won't work". I agree that if you try to run srun on a supercomputing login node you will likely have problems. But that is not what is typically done (see next point).
* the tutorial uses rlaunch whereas the installation sets up an infrastructure for using qlaunch. I am not sure why. Why not just show the user how to use qlaunch? That is what they will be using in production anyway. If your intention is to help the user run a quick test rather than waiting for days in the queue to get the result of the tests, I would suggest to anyway have the docs assume the user is going to run qlaunch (i.e., no restrictions against using srun type commands, use qlaunch -r rapidfire to launch, etc). But in the actual section where it tells you to run the qlaunch command, make a note that saying if you just want to test locally (on the current computer or login node) rather than wait on a queue then use rlaunch instead and make sure the vasp_cmd doesn't include any special commands like srun. But we want the default procedure to be what people are expected to do regularly because that is the pattern they will repeat, and then just make a quick exception for testing purposes.

**Comment by bocklund** [comment]
Yeah this was aimed to be done on the login node because it runs in a few minutes and gets the user to their result in one sitting ( they don't have to wait for the queue). This is best for a tutorial IMO because a beginner will make mistakes and need rapid feedback. People are going to give up if they mess up a few times and can't quickly get through the tutorial. 

I'll update this to make it more clear to use qlaunch except for this quick tutorial where we rlaunch for debugging and quick feedback.

**Comment by computron** [comment]
Ok, I'll review it again after the modifications.
