### ISSUE TITLE
Running workflows docs - example should be more intuitive

### ISSUE THREAD

**Issue by computron** [hackingmaterials/atomate#124]
@bocklund 

The goal of the Running Workflows docs is to demonstrate atomate feeling "magical" - i.e., things that are normally difficult become super easy. i.e., the steps should be short and intuitive. This is our primary example to demonstrate why someone spent so much time installing the software. After that, the rest should be easy.

The example doesn't really demonstrate that.

1. If I were a new user, setting up the eos workflow wouldn't seem like something I could do myself. That YAML file is super complicated containing all sorts of foreign terms like "TransmuterFW" that a new user will have no clue about. And it's also really long and tedious - not exactly short and tidy. I have no idea where to start in terms of looking.
2. If I were a new user, analyzing the eos workflow wouldn't seem like something I could do myself. It seems to require intimate knowledge of what's being put in the database - field names, etc. - and even after that requires quite a bit of extra coding on my part. Feels more like manual labor that requires a *lot* of prior knowledge than magical. And I don't even get the fit of the equation of state at the end, despite the workflow name! So it's pretty much a letdown.

A better example would be:

1. Add a band structure workflow with one line. Either of the below

atwf add Si.cif -p wf_bandstructure
OR
atwf add Si.cif -l vasp -s bandstructure.yaml
OR
atwf add -m mp-149 -p wf_bandstructure

You can take the opportunity to point out all the other preset workflows that are available as Python functions (option 1) or YAML (option 2). e.g., if you just want to optimize, use the optimize_only.yaml file. Plus the YAML file is super clean for those. Also point out that they have access to 60,000 crystal structures if they use the -m option. A newcomer won't think the code is about having huge YAML specifications that are for expert coders.

2. Run using:
qlaunch -r rapidfire

They already met this command in the install tutorial. If they have the ability to run locally (not everyone does, e.g. NERSC officially doesn't allow this even if you can technically do it), then you can point them to rlaunch as well as a vasp_cmd that is more basic (see my other ticket about this)

3. Analyze and plot using pymatgen. I'd suggest something like:

* Use VaspCalcDb to connect to MongoDB
* Use the get_band_structure() and get_dos() methods of the above to get band structure and dos objects
* print out a few attributes of the above objects like band gap or fermi energy
* Use BSDosPlotter() to produce a pretty plot

All 4 of the above steps can probably be done in 10 lines of code or less - with each line being very short and clear about what it's doing (almost like English).

If there are more complex analysis that require digging into the database, you can demonstrate those too. But it shouldn't be the first thing the user is exposed to and the user shouldn't get the feeling that is what's needed to extract useful information from atomate workflows.

For the current EOS example, I'd suggest:
- encouraging a preset workflow instead of the YAML format, which misses the all-important fitting portion (and one of the great benefits of using atomate)
- having the analysis be little more than querying the database for the result or inspecting the JSON file in the result directory. You can also give an example of manual analysis for the brave (retain the current analysis) but again one should not get the impression that this is what is expected.

**Comment by bocklund** [comment]
What do you think about moving the YAML to its own tutorial not on the main track? I think it's useful to see if you really want a YAML file. If a user wanted to make a workflow, they would want to do so because their calculation is non-trivial and all of the existing workflow YAML files are nice and short, but trivial. 

So I'll rework running workflows to not include a YAML file with atwf at all - the installation did that already. 

Also a good suggestion to use VaspDbCalc. 

Removing the YAML will make the tutorial shorter, so I think both workflows would be nice.

**Comment by computron** [comment]
Hi @bocklund 

A separate YAML tutorial sounds good to me. The atwf might still be useful, but perhaps with one of the prebuilt workflows from either the "presets" module or the library of pre-existing YAML files (see Option 1 in my revised docs). It's also a good entry-way to say that if you want to learn more about creating and editing your own YAML files, you can see the separate doc about that.

Even in the YAML tutorial I'd start simple - like the band structure one or similar. I wouldn't open with the elastic one.

I'll review again when you're finished - thanks!
