### ISSUE TITLE
Needed docs: builders

### ISSUE THREAD

**Issue by computron** [hackingmaterials/atomate#126]
A short doc on builders would be useful, it's one of the core features of atomate

**Comment by bocklund** [comment]
I have not used the builders before. I can probably write a simple tutorial, but it may need a second look to better describe the bigger picture

**Comment by computron** [comment]
Hi @bocklund . I can probably get a basic builders tutorial up and running at some point, but it might be a few weeks time. The issue is here as a reminder

**Comment by computron** [comment]
@bocklund I started some basic docs, will close this for now but feel free to add more desired. If you haven't started trying out the builders I'd very much recommend starting
