### ISSUE TITLE
atomate/vasp/firetasks/parse_outputs.py imports and uses non-existing IndependentStrain from pymatgen

### ISSUE THREAD

**Issue by bocklund** [hackingmaterials/atomate#133]
## System

* Version: master
* Python version: 2.7.12
* OS version: Linux

## Summary

atomate/vasp/firetasks/parse_outputs.py imports and uses IndependentStrain from pymatgen, but pymatgen doesn't seem to have any such class. Looks like there are also some usages in pymatgen. @montoyjh 

I have pymatgen 2017.7.4 installed.

**Comment by montoyjh** [comment]
Pymatgen 2017.7.4 has IndependentStrain.  See the release code [here](https://github.com/materialsproject/pymatgen/blob/fe4149e2af0ab52362a2e5e551cb4a3b4508be40/pymatgen/analysis/elasticity/strain.py).

If you're referring to the current pymatgen git repo, atomate will be adapted to reflect those changes pending the next pymatgen release.

**Comment by bocklund** [comment]
Looks like I am actually using the dev version. Thanks!
