### ISSUE TITLE
Use git lfs

### ISSUE THREAD

**Issue by shyuep** [hackingmaterials/atomate#138]
This repo is getting pretty big, and will only get bigger as we  add more workflows with chgcars, etc. I suggest we move to using git lfs for faster clones and pulls. It is pretty transparent, and the only requirement is that the developers have to install git lfs first. I have already implemented lfs support with a custom image for testing.

Pymatgen has already moved to a git lfs system. The impetus is even stronger for atomate.

**Comment by computron** [comment]
I played around with git-lfs for matminer and find it to not be very smooth and create problems, especially for existing repo files. e.g., clones fail

**Comment by shyuep** [comment]
OK I agree.
