### ISSUE TITLE
atwf and "files" serialization of workflows doesn't make it easy to set vasp command

### ISSUE THREAD

**Issue by computron** [hackingmaterials/atomate#143]
@bocklund @shyuep - this relates to your part of atomate

## Summary

* The documentation for atomate suggests that users create their first workflow using the command: ```atwf add -l vasp -s optimize_only.yaml -m mp-149```
* Unfortunately, this command does not honor the "vasp_cmd" set up in my_fworker.yaml and just runs "vasp" as the executable (making the set up of my_fworker.yaml pointless)
* I don't see any easy way for the user to put in their vasp_cmd. They can edit optimize_only.yaml to add a ``common_params`` but that is clunky - they need to locate the file and edit it. I actually think it less of a pain to just use Python in that case.
* This has led to user failures in trying to follow the atomate tutorials

## Example code

See this thread:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/atomate/xVghmE3YOco

## Suggested solution (if any)

Possible solutions include:

* Replace the docs command with the one suggested in the Google Groups thread (```atwf add -l vasp -p wf_bandstructure -m mp-149```). This will at least stop initial users from seeing errors right away but then the tutorial is more about preset function based workflows than file-based workflows
* Edit all the file-based workflows in the library so that the common_params has vasp_cmd set to ">>vasp_cmd<<". Kind of a pain and everyone that needs to do this for all file-based workflows
* Allow atwf to set common_params during the command line command itself. Something similar to (``atwf add -l vasp -s optimize_only.yaml -m mp-149 --common_params vasp_cmd=">>vasp_cmd<<"). Again a little clunky and non-intuitive, but it would work

There are probably other solutions but those are 3 possibilities

**Comment by shyuep** [comment]
I would suggest doing a combination of (2) and (3). I see a lot of the yaml files having specific vasp_cmd which probably will never work in any system other than the ones that they are written for.

I haven't been keeping up but how does >>vasp_cmd<< actually work? i.e., which code replaces that with the actual command to be used, and what config file is that set in? I see mention of it in config.py, but that seems hard coded.

**Comment by computron** [comment]
This is the "env_chk" functionality, more details here:
https://hackingmaterials.github.io/atomate/concepts.html

In essence, the actual FireTask that you are coding will take your desired String for the VASP executable and pass it through a function in atomate called env_chk. The FireTask code itself is running your parameter through env_chk.

* If your String looks like this: ">>something<<", it will replace "something" with the value of your fw_env's "something" key (set by my_fworker.yaml). This allows "something" to change for different machines by setting different values in the different my_fworker.yaml.
* If your String doesn't look like the above, it is just pass-through. So if you set it to "something", it just stays "something". Thus, the env_chk doesn't interfere with hard-coding any parameters you just wanted hard-coded.

**Comment by computron** [comment]
Closing via: 	38b7c9601a8e1c003136d64b28f00cf37df02404
