### ISSUE TITLE
Serialized VaspInputSets don't contain user_incar_settings added after instantiation

### ISSUE THREAD

**Issue by bocklund** [hackingmaterials/atomate#167]
It is sometimes the case that I would like to use one customized input set as a base and change the parameters (e.g. ISIF) programmatically later down the line.
The most straightforward way I can see to do this is to update the `user_incar_settings` dict after instantiating the input set. 
In code, what I want to do is:

``` python
def relax_743(structure, my_input_set):
    vis1 = copy(my_input_set)
    vis1.user_incar_settings.update({'ISIF': 7})
    fw1 = OptimizeFW(structure, vasp_input_set=vis1)

    vis2 = copy(my_input_set)
    vis2.user_incar_settings.update({'ISIF': 4})
    fw2 = OptimizeFW(structure, vasp_input_set=vis2, parents=fw1)

    vis3 = copy(my_input_set)
    vis3.user_incar_settings.update({'ISIF': 3})
    fw3 = OptimizeFW(structure, vasp_input_set=vis3, parents=fw2)
    
    fws = [fw1, fw2, fw3]
    return Workflow(fws)
```

When doing this, serializing the input sets doesn't work:

```python
from pymatgen import Structure
from pymatgen.io.vasp.sets import MPRelaxSet

### Setting during initialization

vis = MPRelaxSet(Structure.from_file('POSCAR'), user_incar_settings={'ISIF': 7})

print(vis.as_dict()['user_incar_settings'])
# prints:
# {'ISIF': 7}


### Setting after initialization

vis = MPRelaxSet(Structure.from_file('POSCAR'))

print(vis.user_incar_settings)
# prints (as expected, we didn't set any user incar settings)
# {}

vis.user_incar_settings.update({'ISIF': 7})
print(vis.user_incar_settings)
# prints (as expected, we just set this)
# {'ISIF': 7}

print(vis.as_dict()['user_incar_settings'])
# KeyError! The INCAR settings are not serialized
```

@shyuep is this the intended behavior of the VaspInputSets?

If it is the intended behavior, is there a better way to do this? In atomate, we pass everything by instance, but maybe we should instantiate inside the `Firework.__init__` method (for the subclass of Firework) and instead pass the *class* `MPRelaxSet` rather than an instance of `MPRelaxSet` as arguments to the Fireworks?

**Comment by bocklund** [comment]
I know that powerups kind of solve this problem, but it's another degree of complexity and I have to worry about specifying unique names for each of the Fireworks by hand so that I can properly use the `fw_name_constraint` argument to the modify INCAR powerup

**Comment by computron** [comment]
@bocklund check the docs for WriteVaspFromIOSet. You should be able to specify the class name as string and the user_incar_settings as a parameter. But you will need to modify some the FWs like ``OptimizeFW`` to use this option better. For example, the ``**override_default_vasp_params`` in OptimizeFW only operates on the default (MPRelaxSet) and not on a custom vaspinput set, the latter would be preferred.

@shyuep IMO the serialization example that Brandon provides should have worked since ``user_incar_settings`` is public and so he should be allowed to modify it and retain "good" behavior.

**Comment by bocklund** [comment]
@computron Thanks. Yes, this basically what I was getting at regarding the `override_default_vasp_params`, which would ideally work for any input set. Class name as a string is an ok option, but I am subclassing the DictSet base class with some custom parameters that are better suited for our work on metals and the as string option is hardcoded to only look in pymatgen.

**Comment by computron** [comment]
Ok, but you'd likely have to make the code mods yourself since I don't think anyone else will work on it especially in short to mid term

**Comment by computron** [comment]
(also, I would submit the serialization thing to the pymatgen list)

**Comment by shyuep** [comment]
This is not really a bug. The default serialization in MSONable basically only looks at the arguments actually supplied to the Subclass, not the Superclass. user_incar_settings is a kw of the DictSet superclass. 

In general, one should not be modifying these variables that way. The idea is to use the constructor. I am happy to make all the variables private, but just doesn't want to make it more difficult to use.

**Comment by shyuep** [comment]
Also, to add that this really is a feature to avoid too large serialization dicts. While I can make it such that all subclasses include the superclass dict when **kwargs are used, the problem then is that this becomes a huge dict for when superclasses contain a lot of variables. 

One should really think of the serialization as operating on variables that were explicitly specified at init time. For example, if I have a class that only takes in a "a" variable but has a b additional variable that is not init, and a user subsequently sets self.b = 1000, that b value is not serialized.

**Comment by bocklund** [comment]
I think this is sufficiently solved.  Closing.
