### ISSUE TITLE
boltons.copytree() instead of custom function

### ISSUE THREAD

**Issue by computron** [hackingmaterials/atomate#193]
@albalu - I noticed a recent PR of yours implemented a custom ``copytree()`` function. Can you see if the implementation in this library is what you want?

http://boltons.readthedocs.io/en/latest/fileutils.html

If so, you can remove the copytree() code from atomate, add a dependency to boltons (in requirements.txt and setup.py), and use the copytree implemented in boltons.

The boltons library should be pretty lightweight and there might be other functions we want to use in their later, so I don't mind the added dependency.

**Comment by albalu** [comment]
@computron , yes the implementation is exactly the same. I resolved this issue via PR #194 .

**Comment by computron** [comment]
Thanks!
