### ISSUE TITLE
additional_fields parameters to the Vasp calculations fireworks in atomate/vasp/fireworks/core.py

### ISSUE THREAD

**Issue by richardtran415** [hackingmaterials/atomate#198]
An optional parameter to the different fireworks in core.py called additional_fields will give the user more control over what information gets stored in their DB. By default, additional_fields={} which just stores {"task_label": name} as an additional field. This is just so users don't have to rewrite something like the OptimizeFW just so they can create their own additional_fields.

**Comment by computron** [comment]
You should use ``add_additional_fields_to_taskdocs`` for this

**Comment by computron** [comment]
(the existing powerup)

**Comment by richardtran415** [comment]
I see, thanks
