### ISSUE TITLE
boltons

### ISSUE THREAD

**Issue by shyuep** [hackingmaterials/atomate#201]
Someone needs to fix the conda yaml for atomate. Boltons was introduced as a dependency, but not added to the conda yaml. Right now, atomate cannot be built.

In any case, I am not sure why the need for boltons. AS far as I can see, the only use is boltons.fileutils.copytree. Based on the doc, this is an exact replica of shutil.copytree with the exception that it does not raise an Exception if part of the tree exists. This sounds to be like a rather trivial thing to work around instead of introducing a new dependency.

**Comment by albalu** [comment]
I can add boltons as requirement to conda yaml. Could you please point me to this file? I couldn’t find anything on atomate repo.

I think we want to use more than just copytree from boltons in the future and that was the logic for adding it as a requirement.

**Comment by shyuep** [comment]
I think rather than thinking about "future" uses, we worry about today's use. If there is no need for boltons, keep it out for now until you find an overwhelming use case for it.

**Comment by shyuep** [comment]
I should also point out that monty has a somewhat similar function called monty.shutil.copy_r

**Comment by shyuep** [comment]
See https://pythonhosted.org/monty/monty.html?highlight=copy_r#monty.shutil.copy_r

**Comment by albalu** [comment]
ok that looks good. Thanks, I will use that instead.

**Comment by albalu** [comment]
#202 should solve this issue.
