### ISSUE TITLE
fix CircleCI tests so that VASP integration tests are also run

### ISSUE THREAD

**Issue by computron** [hackingmaterials/atomate#204]
It seems the CircleCI integration tests skip most of the tests. Probably this is because running VASP tests (even the simulated VASP runs) requires MongoDB (think this is already set up and so shouldn't be a problem) and also VASP POTCAR files with associated set up of PMG_VASP_PSP_DIR (probably the issue).

**Comment by shyamd** [comment]
Are you sure the MVL CircleCI image has MongoDB? When I run nosetest on my computer with mongod they run, but when I kill mongod they get skipped, just like on CircleCI

@shyuep can you comment on this?

**Comment by computron** [comment]
@ardunn any thoughts on this since you just upgraded CircleCI for FWS and matminer?

**Comment by computron** [comment]
@ardunn please update. Things like LAMMPs workflows look to be broken, which people on the atomate list are asking about, and no one is aware of what's broken / working since the tests are not being run properly with CircleCI.

**Comment by ardunn** [comment]
@computron whoops did not see original comment. Maybe this is something to address during codebusters. Should be doable with some input from some VASP-familiar people. From what I know, CircleCI is Docker capable, so that may be a way to do this.

**Comment by computron** [comment]
Note - you don't need VASP to run the tests, just have MongoDB running and also (maybe) set a couple of environment variables(?). i.e. you can run the atomate tests locally on your computer with MongoDB running w/o VASP installed.

**Comment by ardunn** [comment]
Oh I see. In that case, I don't see any reason why this would not work. I'll add to codebusters issue list

**Comment by computron** [comment]
ok - it should already be on the list

**Comment by ardunn** [comment]
@computron see #242
