### ISSUE TITLE
get_settings error when using any builder

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/atomate#206]
## System

* Version: "master"
* Python version: 2.7.13, 3.6.2
* OS version: MacOS 10.13.3

## Summary

* Error whenever creating a builder object
* Throws error whether using db from file or a writable collection passed as arg

## Example code

```python
from atomate.vasp.builders.fix_tasks import FixTasksBuilder
DB_FILE = "/Users/me/path/to/db.json"
fix = FixTasksBuilder.from_file(DB_FILE)
```

## Error message

```
Traceback (most recent call last):
  File "/Users/ardunn/alex/lbl/projects/thermoelectrics/code/thermoelectrics_work/thermoelectrics_work/build_te_database.py", line 28, in <module>
    fix = FixTasksBuilder.from_file(DB_FILE)
  File "/Users/ardunn/alex/lbl/projects/common_env/common_env/lib/python2.7/site-packages/atomate/vasp/builders/fix_tasks.py", line 72, in from_file
    db_write = get_database(db_file, admin=True)
  File "/Users/ardunn/alex/lbl/projects/common_env/common_env/lib/python2.7/site-packages/atomate/utils/utils.py", line 338, in get_database
    d = get_settings(config_file) if settings is None else settings
NameError: global name 'get_settings' is not defined
```

## Suggested solution (if any)

* Define`get_settings` ? Not sure
@albalu

**Comment by albalu** [comment]
Yes I am not sure where this get_setting should come from pycharm finds 3 different sources for it including matgendb.dbconfig is that the correct address? Also seems like MongoClient needs to be imported which is minor. What about _log? My guess is that get_database was moved to atomate.atomate.utils.utils recently but these functions are not imported?

**Comment by computron** [comment]
@shyamd is this related to your refactoring to take out matgendb?

I presume it is an accident that it happens to break the competing builders technology? lol

**Comment by shyamd** [comment]
Yeah, total accident. I thought I had the imports properly ported since the tests were all working out. Should be a simple fix.

**Comment by shyuep** [comment]
Erm, I am confused. Why are pymatgen-db causing conflicts on imports?

**Comment by shyamd** [comment]
It was when the changes were made. Question for @computron: Shall I re-factor pymatgen-db as a dependency again or leave it out?

**Comment by computron** [comment]
I think the get_settings() function usage in that atomate function is not doing much? is it functioning the same as a json.load()?

Also there is a line that says ``_log.warn(`` which is going to be an error since ``_log`` was never defined. And there is no docstring for that function. Sorry to say but that function is a train wreck...

**Comment by computron** [comment]
(and Alireza's comment about MongoClient needing to be imported)

I suggest that people start using an IDE. It will put angry red underlines to prevent these kinds of errors.

**Comment by shyamd** [comment]
this should be fixed. Any update?

**Comment by computron** [comment]
@ardunn please check and close issue if fixed

**Comment by ardunn** [comment]
Yes this is fixed.
