### ISSUE TITLE
spec_path is wrong when atwf script gets copied instead of run via a wrapper

### ISSUE THREAD

**Issue by migueldiascosta** [hackingmaterials/atomate#208]
## System

* Version: 0.7.0
* Python version: 2.7.14, 3.6.4
* OS version: CentOS 6.9

## Summary

* The `atwf` script uses  `os.path.abspath(__file__)` to define `module_dir` and build `spec_path`.

* Usually (e.g. when atomate is installed directly via `setup.py`), a wrapper is created (by `setuptools`) which uses `pkg_resources.run_script` to run the `atwf` script from the `atomate/scripts` folder, and the `spec_path` is correct. 

* However, in some cases (here, when atomate is installed with pip in a virtualenv), the `atwf` script gets copied verbatin to the `venv/bin` folder, and `spec_path` is therefore wrong. 

## Suggested solution 

* Not sure if this is an issue with `atomate`, `pip`, `setuptools` or `virtualenv`, but maybe building `module_dir` from `os.path.abspath(atomate.__file__)` instead of `os.path.abspath(__file__)` would be more robust (?)

**Comment by computron** [comment]
Thanks for reporting this! Do you want to submit a pull request with the suggested change, or would you prefer I do it?

**Comment by migueldiascosta** [comment]
ended up using the already imported `atomate.vasp.workflows.presets.core` instead of `atomate` to avoid polluting the namespace, do let me know if you prefer otherwise (there's definitely more than one way of skinning this cat)

**Comment by computron** [comment]
Thanks! It looks good to me, I merged.
