### ISSUE TITLE
custodian gzip breaks offline mode

### ISSUE THREAD

**Issue by computron** [hackingmaterials/atomate#215]
atomate cannot be run in offline mode with the gzip option of custodian on - custodian will zip up FW_offline.json -> FW_offline.json.gz, which causes FWS to not detect the offline file when recovering jobs.

Potential fixes
1. make it easier to turn off gzip and alert people in the docs this is necessary in order to use offline mode (not a preferred solution)
2. have FWS support FW_offline.json.gz so it doesn't matter if the file is gzipped or not
3. prevent / avoid having custodian gzip the FW_offline.json file in atomate.

Probably 2 is the best solution?

**Comment by shyuep** [comment]
2 is quite trivial to do if you use monty.io.zopen. Not sure why that isn't the default in any case.....

**Comment by computron** [comment]
Closed by method (2), not quite as trivial as mentioned because both reading/writing needs to be done to these binary files.

See:

d391755e62e4de1f1b79bfb7c08867d491806533
7ce36539ce5851e10f13af09052b270b7e9d0ed3
c7044f87cee770545e19eddb2f2641f92106a440
