### ISSUE TITLE
Max force error in drone defuses children for amorphous structures

### ISSUE THREAD

**Issue by shyamd** [hackingmaterials/atomate#218]
There's some error analysis code in the drone that checks for max_forces and if its over a certain amount it sets the calculation state to error. This is especially problematic for amorphous structures which are often optimized very loosely. As a result a lot of amorphous optimizations "error" at the drone state and defuse children.

The max_force_threshold in the optimization firework should somehow propagate to the drone, and behave in the same way across custodian and the drone, e.g. None means ignore this.

**Comment by computron** [comment]
Agreed, someone just has to implement

**Comment by shyamd** [comment]
The offending lines of code are:
`            if max_force > max_force_threshold:
                error_msgs.append("Final max force exceeds {} eV".format(max_force_threshold))
                d["state"] = "error"

            s = Structure.from_dict(d["output"]["structure"])
            if not s.is_valid():
                error_msgs.append("Bad structure (atoms are too close!)")
                d["state"] = "error"
`
If I run a calculation where I intentionally put in a bad structure or i'm not trying to converge all that well on forces, this code will prevent me from doing so. Is there a specific reason the drone effectively throws an error along with recording an error message?

**Comment by shyamd** [comment]
An added case seems to be using Phonopy QHA mode with the Gibbs workflow where  DFPT calcs on volume deformations have to run without NSW being set and yield nonsensical forces causing the drone to throw an error.

In general, this seems to be a weird check that I'm not sure why its there. In the pymatgen drone it makes sense, since the calc could come from anywhere but in atomate the drone is formatted logic for our workflows? I'm happy to make this change, but I'm tempted to just throw the check out since it doesn't seem to fit in with our workflow paradigm unless I'm wrong?

**Comment by computron** [comment]
From what I can tell, custodian already checks for max_force

Assuming that's the case, I don't think it's needed again in the drone. Thus the "proper" way to turn off or on a max_force check would be to just to do it through custodian. The RunVaspCustodian task has a parameter that you could control.

Is this the behavior you'd want? If so feel free to implement and push a PR

**Comment by computron** [comment]
Closed via:

https://github.com/hackingmaterials/atomate/pull/227
