### ISSUE TITLE
NEB Test fails on CircleCI

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/atomate#243]
NEB test fails on CircleCI. It will be skipped necessarily after #242 is merged.

```
======================================================================
FAIL: test_wf (atomate.vasp.workflows.tests.test_neb_workflow.TestNudgedElasticBandWorkflow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/atomate/atomate/vasp/workflows/tests/test_neb_workflow.py", line 128, in test_wf
    self.assertTrue(all([s == 'COMPLETED' for s in wf.fw_states.values()]))
AssertionError: False is not true
```

**Comment by itsshawnzhang** [comment]
Since the PR has merged and CircleCI works well for now, I will close this issue. Please let us know for any further problems or concerns. Cheers! :)

**Comment by ardunn** [comment]
Ok sounds good! TBH this is issue is so ancient I don't even know it what it is about. But if tests pass, this is a good thing (hopefully!)
