### ISSUE TITLE
Should LAMMPS in Atomate be deprecated

### ISSUE THREAD

**Issue by wood-b** [hackingmaterials/atomate#245]
Lammps in atomate was a project @matk86 and I started. At the time my research project seemed like it necessitated that, but in the end I went a different direction and the code was never really finished. I don't think either @matk86 or I am interested in maintaining/updating Lammps in atomate (at least in the next 6-8 months). So it seems like we should deprecate it unless someone wants to take over. 

I recently heard from @adengz that he is going to overhaul the lammps io in pymatgen (which can certainly be improved), but the most recent commits break the lammps atomate tests. So a little motivation to upgrade/fix or deprecate.

Thoughts???
@shyuep @computron 

Please submit help issues to:
https://groups.google.com/forum/#!forum/atomate

The Github issues is no longer used except for internal development purposes.

If you are unable to use the Google Group, you may submit an issue here, but you must **clearly** state the reason you are unable to use the Google Group in your ticket. Otherwise, your issue will be **closed** without response.

**Comment by computron** [comment]
I think the conclusion is we should not deprecate LAMMPs and leave it in for now, so I'm closing this.

Feel free to coordinate the development in either a new issue or separate from Github
