### ISSUE TITLE
MaterialsEhullBuilder doesn't use db's results

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/atomate#256]
I have ~50 structures with the same composition. When I go to build their ehulls with `MaterialsEhullBuilder`, curiously I get that twelve of these structures have ehull equal to exactly zero, although their formation energies are different.

It may have something to do with these lines in `vasp.builders.materials_ehull`:

```python
# TODO: @computron This only calculates Ehull with respect to Materials Project.
# It should also account for the current database's results. -computron
self._materials.update_one({"material_id": m["material_id"]}, {"$set": {"stability": 
         self.mpr.get_stability([my_entry])[0]}})
```

Any builder experts have ideas for the best way to go about fixing this?

**Comment by ardunn** [comment]
just realized this is a clone of #234, feel free to close if people want to discuss there instead

**Comment by computron** [comment]
Let's just have it in one place
