### ISSUE TITLE
Wrong saving of "custodian.json"

### ISSUE THREAD

**Issue by gpetretto** [hackingmaterials/atomate#262]
Saving the `custodian.json` to the `stored_data` at the end of a `RunVaspCustodian` task does not work as expected. `stored_data` should be a dict, while `custodian.json` contains a list.
Due to how fireworks handles the stored data in `rocket`
```python
all_stored_data.update(m_action.stored_data)
```
currently in the launch document a `{"job": "correction"}` dictionary is saved.

**Comment by computron** [comment]
Thanks for the report!

What do you think about changing it to:

{"custodian": [[contents of custodian array]]}

**Comment by gpetretto** [comment]
This seems a good solution to me

**Comment by computron** [comment]
I am closing this after the fix
