### ISSUE TITLE
nscf-uniform calculation and data query in MgO band structure tutorial 

### ISSUE THREAD

**Issue by zezhong-zhang** [hackingmaterials/atomate#283]
I was following the MgO band structure [tutorial](https://atomate.org/running_workflows.html). The structure optimisation, statistic calculation and non-self-consistent-line calculations are fine. But for nscf-uniform calculation, vasp fails namelessly as shown in the fig and custodian cannot handle. As suggested by Steven on the google group, it may due to the kpoints generated not matching well with the tetrahedron method ISMEAR=-5.
```python  
# Create a bandstructure from the workflow from the atomate presets
import numpy as np
from pymatgen import Structure
from fireworks import LaunchPad
from atomate.vasp.workflows.presets.core import wf_bandstructure
from atomate.vasp.powerups import add_modify_incar

# load structure from file
struct = Structure.from_file('POSCAR')  # note: many file formats supported, see function docs

# create the Workflow
wf = wf_bandstructure(struct)

# finally, instatiate the LaunchPad and add the workflow to it
lpad = LaunchPad.auto_load() # loads this based on the FireWorks configuration
lpad.add_wf(wf)
```
>Warning & Error Message
WARNING atomate.vasp.drones Transformations file does not exist.
Traceback (most recent call last):
  File "/home/zzhang/atomate/atomate_env/lib/python3.6/site-packages/custodian/custodian.py", line 320, in run
    self._run_job(job_n, job)
  File "/home/zzhang/atomate/atomate_env/lib/python3.6/site-packages/custodian/custodian.py", line 428, in _run_job
    raise CustodianError(s, True, v)
custodian.custodian.CustodianError: (CustodianError(...), 'Validation failed: <custodian.vasp.validators.VasprunXMLValidator object at 0x2aaabc54d2b0>')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/zzhang/atomate/atomate_env/lib/python3.6/site-packages/fireworks/core/rocket.py", line 262, in run
    m_action = t.run_task(my_spec)
  File "/home/zzhang/atomate/atomate_env/lib/python3.6/site-packages/atomate/vasp/firetasks/run_calc.py", line 205, in run_task
    c.run()
  File "/home/zzhang/atomate/atomate_env/lib/python3.6/site-packages/custodian/custodian.py", line 330, in run
    .format(self.total_errors, ex))
RuntimeError: 0 errors reached: (CustodianError(...), 'Validation failed: <custodian.vasp.validators.VasprunXMLValidator object at 0x2aaabc54d2b0>'). Exited...
/home/zzhang/atomate/atomate_env/lib/python3.6/site-packages/pymatgen/symmetry/bandstructure.py:62: UserWarning: The input structure does not match the expected standard primitive! The path can be incorrect. Use at your own risk.
  warnings.warn("The input structure does not match the expected standard primitive! "

<img width="441" alt="Screenshot 2019-04-24 19 12 20" src="https://user-images.githubusercontent.com/13212584/56749078-540b9c80-6781-11e9-8ab3-4cf7cc316b07.png">
<img width="649" alt="Screenshot 2019-04-24 19 11 36" src="https://user-images.githubusercontent.com/13212584/56749115-67b70300-6781-11e9-84d3-68fafa3b324c.png">

I also have a problem with querying the data in the tutorial. 
```python
from atomate.vasp.database import VaspCalcDb
from pymatgen.electronic_structure.plotter import DosPlotter, BSPlotter
PATH_TO_MY_DB_JSON = '/path/to/db.json'
atomate_db = VaspCalcDb.from_db_file(PATH_TO_MY_DB_JSON)
```
```ptyhon
line_bs_entry = atomate_db.collection.find_one({'task_label': 'nscf line', 'formula_pretty': 'MgO'}) 
```
Return None, but the workflow is there and calculation has finished. If I try,
```python
line_bs_entry = atomate_db.collection.find_one()
```
return

> {'_id': ObjectId('5cc022227f39695c8df0e9fc'),
 'links': {'18': [], '19': [], '20': [19, 18], '21': [20]},
 'parent_links': {'19': [20], '18': [20], '20': [21]},
 'nodes': [18, 19, 20, 21],
 'metadata': {'structure': {'@module': 'pymatgen.core.structure',
   '@class': 'Structure',
   'charge': None,
   'lattice': {'matrix': [[2.606553, 0.0, 1.504894],
     [0.868851, 2.457482, 1.504894],
     [0.0, 0.0, 3.009788]],
    'a': 3.0097881143105405,
    'b': 3.0097883300592754,
    'c': 3.009788,
    'alpha': 60.000003627588235,
    'beta': 60.00000125635496,
    'gamma': 60.000003208803285,
    'volume': 19.279368831332597},
   'sites': [{'species': [{'element': 'O', 'occu': 1}],
     'abc': [0.5, 0.5, 0.5],
     'xyz': [1.737702, 1.228741, 3.009788],
     'label': 'O',
     'properties': {}},
    {'species': [{'element': 'Mg', 'occu': 1}],
     'abc': [0.0, 0.0, 0.0],
     'xyz': [0.0, 0.0, 0.0],
     'label': 'Mg',
     'properties': {}}]},
  'nsites': 2,
  'elements': ['Mg', 'O'],
  'nelements': 2,
  'formula': 'Mg1 O1',
  'formula_pretty': 'MgO',
  'formula_reduced_abc': 'Mg1 O1',
  'formula_anonymous': 'AB',
  'chemsys': 'Mg-O',
  'is_ordered': True,
  'is_valid': True},
 'state': 'FIZZLED',
 'name': 'MgO',
 'created_on': datetime.datetime(2019, 4, 24, 8, 45, 20, 989000),
 'updated_on': datetime.datetime(2019, 4, 24, 16, 42, 56, 608000),
 'fw_states': {'21': 'COMPLETED',
  '20': 'COMPLETED',
  '19': 'FIZZLED',
  '18': 'COMPLETED'}}

**Comment by utf** [comment]
Hi @zezhong-zhang, thanks for this very detailed issue.

You are correct that this is due to use of `ISMEAR = -5` for a k-point mesh with no tetrahedron information.

A recent update to the `MPNonSCFSet` class changed the default smearing type to the tetrahedron method however the KPOINTS file is still written without the tetrahedron information.

I am looking into a fix for this now.

**Comment by utf** [comment]
The underlying issue is referenced in materialsproject/pymatgen#1453.

**Comment by zezhong-zhang** [comment]
Hi @utf

Many thanks for bringing this issue into attention. I have checked the discussion, looking forward to the updated MPNonSCFSet.

I think the data query should be a separate issue that I will edit soon.

**Comment by zezhong-zhang** [comment]
Hi @utf,

I have another tested run after the update and the nscf-uniform calculation can now finish. However, the plotted DOS is different from the example, see as attached, while the bandstructure plots properly.

![download-1](https://user-images.githubusercontent.com/13212584/57549262-56feb380-7363-11e9-95e9-8b9171225f17.png)

**Comment by zezhong-zhang** [comment]
Here is the DOS from the tutorial for comparison. 
![](https://atomate.org/_images/MgO-dos.png)

**Comment by bocklund** [comment]
@zezhong-zhang Can you remove the `ylim=(0,0.1)` in the following line of code from the analysis script you got from the tutorial?

```dos_plotter.get_plot(xlim=(-10, 10), ylim=(0, 0.1))```

**Comment by utf** [comment]
Hi @zezhong-zhang, we have updated the default density of states smearing parameter (ISMEAR) in the latest update of pymatgen. This accounts for the difference you see in the shape of the density of states. 

As you can see, the new density of states shows much more detail than the previous version, however, I am surprised that the intensity has increased so much.

I will:
- Investigate to check that the increased density of states intensity is physical.
- Update the example so that the example DOS matches the new output of automate.

**Comment by zezhong-zhang** [comment]
Hi @bocklund and @utf, here are the plots without ylimit and xlimit. I also add the calcualted Fermi level and bandgap.

Fermi energy: 3.93249361 eV
Bandgap: 4.5851999999999995 eV

<img width="913" alt="Screenshot 2019-05-10 21 04 47" src="https://user-images.githubusercontent.com/13212584/57550870-dc846280-7367-11e9-82b3-06d83608ff63.png">

<img width="902" alt="Screenshot 2019-05-10 21 10 14" src="https://user-images.githubusercontent.com/13212584/57550962-16556900-7368-11e9-9d92-ebcfe32d5634.png">

**Comment by zezhong-zhang** [comment]
Hi @bocklund and @utf,

Here is the plot without ylim.

![image](https://user-images.githubusercontent.com/13212584/57550630-3cc6d480-7367-11e9-8b70-f361b18e76bc.png)
