### ISSUE TITLE
Tags are not passed to individual fireworks in QChem workflow

### ISSUE THREAD

**Issue by rkingsbury** [hackingmaterials/atomate#576]
This is a bug report to be addressed by internal development. Apologies if it should be redirected to Discourse.

When I create a workflow from `SinglePointFW` or `FrequencyFlatteningOptimizeFW` and assign tags to the workflow, e.g.

```
fw = FrequencyFlatteningOptimizeFW(s)
wf = Workflow([fw], name=wfname, metadata={"tags":["foo","bar"]})
```

The tags are correctly assigned to the `metadata` key of the workflow, but are not passed to the underlying FireWorks. Normally (At least in the VASP workflows), the tags are passed through to the FireWork `spec`. Since queries in `my_fworker.yaml` operate on individual FireWorks, the lack of tagging makes it difficult to find and organize calculations.

If someone can provide guidance on where / how this should be fixed I'd be happy to open a PR.

**Comment by rkingsbury** [comment]
@samblau @espottesmith have you noticed this?

**Comment by utf** [comment]
If you're using VASP, the typical way of adding tags is via the `add_tags` powerup:

```
def add_tags(original_wf, tags_list):
    """
    Adds tags to all Fireworks in the Workflow, WF metadata, as well as
    additional_fields for the VaspDrone to track them later (e.g. all fireworks
    and vasp tasks related to a research project)

    Args:
        original_wf (Workflow)
        tags_list: list of tags parameters (list of strings)

    Returns:
       Workflow
    """

    # WF metadata
    if "tags" in original_wf.metadata:
        original_wf.metadata["tags"].extend(tags_list)
    else:
        original_wf.metadata["tags"] = tags_list

    # FW metadata
    for idx_fw in range(len(original_wf.fws)):
        if "tags" in original_wf.fws[idx_fw].spec:
            original_wf.fws[idx_fw].spec["tags"].extend(tags_list)
        else:
            original_wf.fws[idx_fw].spec["tags"] = tags_list

    # DB insertion tasks
    for constraint in ["VaspToDb", "BoltztrapToDb"]:
        idxs = get_fws_and_tasks(original_wf, task_name_constraint=constraint)
        for idx_fw, idx_t in idxs:
            if "tags" in original_wf.fws[idx_fw].tasks[idx_t]["additional_fields"]:
                original_wf.fws[idx_fw].tasks[idx_t]["additional_fields"][
                    "tags"
                ].extend(tags_list)
            else:
                original_wf.fws[idx_fw].tasks[idx_t]["additional_fields"][
                    "tags"
                ] = tags_list

    return original_wf
```

You can see that the first part adds the tags to the workflow object, the second part adds tags to fireworks, and the third part adds tags to VASP specific `ToDb` FireTasks.

I'd suggest making an equivalent `add_tags` powerup for the QChem module, if it doesn't already exist.

**Comment by samblau** [comment]
As Alex suggests, I always add tags via the add_tags powerup, e.g. :

wf = add_tags(wf, {"class": "smd_production", "time": str(time_tag)})

**Comment by rkingsbury** [comment]
OK, thanks @utf @samblau . The only `add_tags` powerup in atomate is for VASP, but I guess it works for QChem as well? The fact that we didn't have a powerup in `atomate.common.powerups.py` or in `atomate.qchem` led me to believe that the VASP one wouldn't work, which is why I resorted to setting tags directly.

If I'm reading the code snippet above correctly, using the VASP powerup with a QChem firetask would not propagate the tag into the task database. Is there a way we could change

```
for constraint in ["VaspToDb", "BoltztrapToDb"]:
```

to basically regex match any task ending in `ToDb`? Then perhaps we can move this whole powerup into `atomate.common`? It doesn't make sense to me that something as universal as tagging workflows needs to be specific to different codes.

**Comment by samblau** [comment]
I haven't thought deeply about the source code, but in practice the tags do successfully propagate into the task DB.

**Comment by samblau** [comment]
I agree that it would make more sense to me if it were explicitly general and organized to indicate its generality, as @rkingsbury is suggesting.

**Comment by utf** [comment]
The main issue with using a regex is that the ToDb task has to support the additional_fields optional argument, otherwise the workflow will fail to run correctly.

If you want to implement the general case, you should combine the regex with explicit checking of the required/optional params to look to see if the task supports `additional_fields`.

I'm happy to merge a pull request with that change. Although, if you do so, please add a deprecation warning to the `add_tags` powerup in the vasp module saying that the import has been moved to common and will be removed in ~6 months.

**Comment by utf** [comment]
The reason why tags are propagating through to the tasks collection is because the `QChemToDb` FireTask includes the following lines:

```
        if "tags" in fw_spec:
            task_doc.update({"tags": fw_spec["tags"]})
```
