### ISSUE TITLE
add wf_to_graph util?

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/atomate#638]
I stumbled upon this nice little utility for visualizing `atomate` workflows and `fireworks` tasks as a graph.

https://github.com/ardunn/mpworkshop/blob/e2e05fc480ffd405bec2e638bd142b5f75c6bb9f/mp_workshop/atomate.py#L32-L62

I think that would in principle make a nice addition to either `atomate` or `fireworks` unless the new dependency on `graphviz` is a deal breaker? Happy to submit a PR if not.

**Comment by utf** [comment]
Hi @janosh, I've also used this function. It is very useful.

`graphviz` is a quite a large requirement so I think adding it as an optional dependency combined with `monty.dev.requires` would be best.

I also think that Fireworks is more natural home for this function, so I'd add it there, provided @computron is ok with this?

**Comment by computron** [comment]
Ok for me (for FireWorks)

**Comment by janosh** [comment]
@computron Cool! Would [this be the file for it](https://github.com/materialsproject/fireworks/blob/main/fireworks/utilities/dagflow.py)? And then import `graphviz` inside `wf_to_graph` so only people using it would have to install it?

**Comment by utf** [comment]
I don't have any advice on where to put the function. But the better way to handle the optional requirement is to structure the file as:

```python
from monty.dev import requires

try:
    import graphviz
except ImportError:
    graphviz = None


...

@requires(graphviz, "graphviz package required for wf_to_graph.\n"
                                   "Follow the installation instructions here: https://github.com/xflr6/graphviz")
def wf_to_graph(workflow):
    ...
```

**Comment by janosh** [comment]
@utf Thanks for the advice! Does this optional dependency on `graphviz` require any changes to a requirements file?

**Comment by utf** [comment]
You can add a new optional dependency in `setup.py` see here: https://github.com/materialsproject/fireworks/blob/1cb78cf9e2168c5741d2bef03d6a9bdf594b190e/setup.py#L38

E.g., you could add:

```
'graph-plotting': ['graphviz'],
```

**Comment by janosh** [comment]
This is resolved since @utf merged https://github.com/materialsproject/fireworks/pull/437.
