### ISSUE TITLE
wf_bandstructure_plus_boltztrap for BoltzTraP2?

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/atomate#639]
Has someone gone to the trouble of writing an atomate workflow for running BoltzTraP2 and would be able to share it? The current `wf_bandstructure_plus_boltztrap` uses `BoltztrapRunner` from the [soon-to-be-axed](https://github.com/materialsproject/pymatgen/issues/2114#issuecomment-824841551https://github.com/materialsproject/pymatgen/issues/2114#issuecomment-824841551) [BoltzTraP v1 module in pymatgen](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/boltztrap.py) and requires the `x_trans` binary which appears much more difficult to acquire than simply `pip install`ing `BoltzTraP2`.

This question originated in [pymatgen#2114](https://github.com/materialsproject/pymatgen/issues/2114).

**Comment by utf** [comment]
Hi @janosh, as far as I know this doesn't exist. In the future there will be an [amset](https://github.com/hackingmaterials/amset) workflow which will have the option to use a constant relaxation time like in BoltzTraP2.

**Comment by janosh** [comment]
Even better! Estimating relaxation times was one of the main pain points so far. Really to try the amset workflow. Can you give any guidance when it might become available and is there something I can do to help (e.g. testing)?
