### ISSUE TITLE
How to add metadata to workflow?

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/atomate#659]
What's the recommended way of adding top-level metadata to fireworks? With top level, I mean directly accessible as a key-value pair in the entries returned by the tasks collection after calculations have finished.

My use case is adding the MP `material_id` for further analysis and comparison. Doing

```py
wf.metadata["mp_id"] = material_id
```

does not convey the id into the database. Using

```py
wf = add_tags(wf, [material_id])
```

_does_ insert the tags into MongoDB but is suboptimal because all tags end up in a column of lists when converted to a dataframe. A list column is much harder to deal with than a column of primitive types, and it can't be parsed into separate columns with `pd.json_normalize` the way a dict could.

**Comment by janosh** [comment]
FWIW, for now I'm doing

```py
for fw in wf.fws:
    assert isinstance(fw.tasks[-1], VaspToDb), "unexpected final task in firework"
    fw.tasks[-1]["additional_fields"]["mp_id"] = material_id
```

which seems to work but is probably brittle and may have side-effects I'm unaware of.

**Comment by janosh** [comment]
Maybe something like this would make sense to have in `atomate`?

```py
def add_metadata(wf, meta_dict):
    """
    Add a metadata dictionary to a workflow and all its Fireworks as well as
    additional_fields in ToDb tasks for the Drone to track them later.

    The dictionary is merged into the "_spec" key of each Firework in the workflow and
    into the "metadata" key of each Workflow. If the workflow contains any
    Firetasks ending in "ToDb", e.g. VaspToDb, QChemToDb, etc., then the dictionary
    is also merged into "additional_fields" of these tasks and included in the
    resulting task documents.

    Args:
        wf (Workflow)
        meta_dict: dictionary of custom metadata

    Returns:
       Workflow
    """

    # add metadata to workflow metadata
    wf.metadata.update(meta_dict)

    # add metadata to firework metadata
    for idx_fw in range(len(wf.fws)):
        wf.fws[idx_fw].spec.update(meta_dict)

    # add metadata to DB insertion tasks
    for idx_fw, idx_t in get_fws_and_tasks(wf, task_name_constraint="ToDb"):
        if "additional_fields" in wf.fws[idx_fw].tasks[idx_t].optional_params:
            wf.fws[idx_fw].tasks[idx_t]["additional_fields"].update(meta_dict)

    return wf
```

**Comment by utf** [comment]
In `atomate.vasp.powerups` there is

```
def add_additional_fields_to_taskdocs(
    original_wf, update_dict=None, task_name_constraint="VaspToDb"
):
    """
    For all VaspToDbTasks in a given workflow, add information  to
    "additional_fields" to be placed in the task doc.

    Args:
        original_wf (Workflow)
        update_dict (Dict): dictionary to add additional_fields
        task_name_constraint (str): name of the Firetasks to be modified.

    Returns:
       Workflow
    """
    idx_list = get_fws_and_tasks(original_wf, task_name_constraint=task_name_constraint)
    for idx_fw, idx_t in idx_list:
        original_wf.fws[idx_fw].tasks[idx_t]["additional_fields"].update(update_dict)
    return original_wf
```

I would edit your powerup to remove the task doc stuff as the naming is different (`additional_fields` vs `metadata`) and could get confusing.

Other than that, I'd be happy to accept that powerup in a pull request.

**Comment by janosh** [comment]
Somehow I didn't find `add_additional_fields_to_taskdocs` even though [the docs have it at the top](https://atomate.org/atomate.common.html?highlight=add_additional_fields_to_taskdocs#module-atomate.common.powerups) but it's exactly what I need! 🤦  Thanks for showing me.

Happy to submit the `add_metadata` powerup if you think there's value in it. If you remove the `additional_fields` there isn't much left to it though... your call.

```py
# after removing additional_fields
def add_metadata(wf, meta_dict):
    """
    Add a metadata dictionary to a Workflow and all its Fireworks. The dictionary
    is merged into the "_spec" key of each Firework in the workflow and into the
    "metadata" key of the Workflow.

    Args:
        wf (Workflow)
        meta_dict: dictionary of custom metadata

    Returns:
       Workflow
    """

    # add metadata to workflow metadata
    wf.metadata.update(meta_dict)

    # add metadata to firework metadata
    for fw in wf.fws:
        fw.spec.update(meta_dict)

    return wf
```

**Comment by utf** [comment]
I still think there is use in that powerup, although I would add a  fw_name_constraint option! Thanks.

**Comment by janosh** [comment]
Alright then. Btw, I think `add_wf_metadata` is a little confusingly named. Based on the name, you would expect it to do what `add_metadata` does. What it actually does is add structure metadata to a workflow.

Not sure how much migration pain that would be but perhaps it should be renamed `add_structure_metadata_to_wf` long-term. What's your take on that?

**Comment by utf** [comment]
Agreed that the name is terrible. `add_wf_metadata` is pretty widely used though, so I think it is best to keep it as is for now.

**Comment by mkhorton** [comment]
Yes, agreed. I fear that when we see something like a bad name, the tendency is to want to refactor which would break existing workflows, whereas just writing better documentation would probably be the better course of action in many cases.
