### ISSUE TITLE
Atomate in offline mode

### ISSUE THREAD

**Issue by JaGeo** [hackingmaterials/atomate#709]
Hi all, 

I am trying to run atomate in the offline mode. I know it is not supported anymore but I think it is very useful for clusters where there are problems with access to MongoDB databases.

There are some issues due to dicts that are not json-serializable (they will be written into FW_offline.json later and the objects that are restored due to loadfn make problems):
For example, here: 
https://github.com/hackingmaterials/atomate/blob/9ff56e5850cb4a03470383cbdd9c5d6e1dd18331/atomate/vasp/firetasks/run_calc.py#L302

(Probably also in my Lobster classes – I am not this far yet)

And, task.json files are not exported correctly if one is in offline mode. db_file exists in offline mode but there is no connection to the database which leads to problems:
e.g., 
https://github.com/hackingmaterials/atomate/blob/cf04d75ab75ffc565cc160df96c81de751eee4b1/atomate/vasp/firetasks/parse_outputs.py#L138

(And, at a lot of different positions throughout the code…)

Is there an interest in including my fixes that allow to run atomate in offline mode? So far, standard VASP runs seem to complete correctly. I will do some more tests. As this comment would be directly related to the development of atomate, I am asking this here. I hope this is okay.

Best, 
JG

**Comment by mkhorton** [comment]
Hi @JaGeo, if the fixes need to be in atomate rather than in FireWorks, it might be good to co-ordinate with @utf on the [atomate2](https://github.com/hackingmaterials/atomate2) repo.

**Comment by JaGeo** [comment]
Hi Matt, yes, they would be in atomate. Thank you for pointing out atomate2.

**Comment by utf** [comment]
Hi @mkhorton, in atomate2 we made the decision to drop support for offline mode. It is not widely used and it breaks many of the workflows. 

However, `jobflow` (on which atomate2 is built) allows you to use alternative databases (including a json file) for passing information between jobs - basically, any maggma store is supported. So I suppose you could use atomate2 with a local database instead of remote one.
