### ISSUE TITLE
use_custodian() overwrites modify_gzip_vasp(wf, False)

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/atomate#719]
If `use_custodian` follows `modify_gzip_vasp(wf, False)`, it overwrites the `False` and defaults it to `True`.

```py
wf = modify_gzip_vasp(wf, False)
wf = use_custodian(wf, custodian_params={"what": "ever"})
```

All fireworks in `wf` will now gzip their output. Maybe this is intentional but I think a better behavior would be for `use_custodian` to leave any value for `gzip` it finds as is.

**Comment by mkhorton** [comment]
I don't believe this is intentional.
