### ISSUE TITLE
R2SCAN Workflow has inconsistent vdW settings

### ISSUE THREAD

**Issue by arosen93** [hackingmaterials/atomate#774]
https://github.com/hackingmaterials/atomate/blob/387938da7c578481c41aa4cfeb65a166778e6372/atomate/vasp/fireworks/core.py#L236-L246

In this code, `BPARAM` is set to 15.7 if the user specified `vdw` in their input params. However, this is the parameter to get SCAN+rVV10. If you want r2SCAN+rVV10, `BPARAM` should be set to 11.95. So, this value should vary depending on the functional. See https://www.vasp.at/wiki/index.php/Nonlocal_vdW-DF_functionals

CC @janosh, @rkingsbury

**Comment by rkingsbury** [comment]
Great catch @arosen93 ! This is a relic from when I originally wrote the workflow, before r2 SCAN had been released. Should definitely be updated now with logic to pick the correct parameters based on functional.
