### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/atomate#782]
[Current release](https://github.com/hackingmaterials/atomate/releases/tag/v1.0.3) fails with

```py
atomate/vasp/drones.py:19
     17 from monty.io import zopen
     18 from monty.json import jsanitize
---> 19 from monty.os.path import which
     20 from pymatgen.apps.borg.hive import AbstractDrone
     21 from pymatgen.command_line.bader_caller import bader_analysis_from_path

ImportError: cannot import name 'which' from 'monty.os.path'
```

`which` was removed from `monty` a long time ago in favor of `shutil.which`. The `main` branch no longer imports it from `monty` but the last release from Feb 2022 still does.

**Comment by Zhuoying** [comment]
@janosh Thanks for the reminder. Yeah, we will need a new release soon for all PRs merged recently and compatibility with up-to-date pymatgen, custodian, etc.
