### ISSUE TITLE
Symmetry reduced elasticity workflow

### ISSUE THREAD

**Issue by montoyjh** [hackingmaterials/atomate#83]
## Summary

* Elastic workflow should have an option for reduction of fireworks according to symmetry

I'm working on this and have a solution implemented, but am in the process of benchmarking and constructing a unit-test.  Just wanted to put into the issue tracker so other folks know it's in the works.

**Comment by computron** [comment]
@montoyjh any update on this ticket?

**Comment by montoyjh** [comment]
Yes, I made a bad decision to lump several new elements of the functionality into a single branch, which is why it's taken so long.  Will also have a few prerequisite pymatgen PRs prior to the atomate one.  Should have something in the next couple of weeks.

**Comment by montoyjh** [comment]
Resolved via [this PR](https://github.com/hackingmaterials/atomate/pull/136).
